// AUTOGENERATED FILE - DO NOT EDIT

var pt = window.PropTypes;
var pk = window['dash_component_editor'];

pk.Editor.propTypes = {id:pt.oneOfType([pt.string]),
 setProps:pt.oneOfType([pt.any]),
 data:pt.any,
 value:pt.any};
